### ISSUE TITLE
Remove gil-refs feature for pyo3

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#10676]
This requires fixing hundreds of warnings. Ideally we will do this in many small PRs, perhaps file at a time.

If you're interested in contributing:

- Edit `src/rust/Cargo.toml` to remove the `gil-refs` feature
- Try compiling (`nox -e local`)
- Fix an error
- Send a PR!

### Progress:

- 4/3: 5 previous errors; 531 warnings emitted
- 4/4: 5 previous errors; 359 warnings emitted
- 4/5: 3 previous errors; 105 warnings emitted
- 4/6: 25 previous errors; 1 warning emitted

```[tasklist]
### Phase 1
- [ ] https://github.com/pyca/cryptography/pull/10711
- [ ] https://github.com/pyca/cryptography/pull/10696
- [ ] https://github.com/pyca/cryptography/pull/10700
- [ ] https://github.com/pyca/cryptography/pull/10703
- [ ] https://github.com/pyca/cryptography/pull/10702
- [ ] https://github.com/pyca/cryptography/pull/10714
- [ ] https://github.com/pyca/cryptography/pull/10715
- [ ] https://github.com/pyca/cryptography/pull/10721
- [ ] https://github.com/pyca/cryptography/pull/10722
- [ ] https://github.com/pyca/cryptography/pull/10725
- [x] `src/backend/hashes.rs`
- [ ] https://github.com/pyca/cryptography/pull/10726
- [ ] https://github.com/pyca/cryptography/pull/10717
- [ ] https://github.com/pyca/cryptography/pull/10719
- [ ] https://github.com/pyca/cryptography/pull/10728
- [ ] https://github.com/pyca/cryptography/pull/10729
- [ ] https://github.com/pyca/cryptography/pull/10678
- [ ] https://github.com/pyca/cryptography/pull/10730
- [ ] https://github.com/pyca/cryptography/pull/10723
- [ ] https://github.com/pyca/cryptography/pull/10684
- [ ] https://github.com/pyca/cryptography/pull/10686
- [ ] https://github.com/pyca/cryptography/pull/10712
- [ ] https://github.com/pyca/cryptography/pull/10745
- [ ] https://github.com/pyca/cryptography/pull/10688
- [ ] https://github.com/pyca/cryptography/pull/10687
- [x] `src/pkcs7.rs`
- [ ] https://github.com/pyca/cryptography/pull/10754
- [x] `src/x509/certificate.rs`
- [x] `src/x509/common.rs`
- [x] `src/x509/crl.rs`
- [x] `src/x509/csr.rs`
- [x] `src/x509/extensions.rs`
- [x] `src/x509/ocsp_req.rs`
- [x] `src/x509/ocsp_resp.rs`
- [ ] https://github.com/pyca/cryptography/pull/10713
- [x] `src/x509/sign.rs`
- [x] `src/x509/verify.rs`
```

```[tasklist]
### Lifetimes
- [ ] https://github.com/pyca/cryptography/pull/10778
- [ ] https://github.com/pyca/cryptography/pull/10757
- [ ] https://github.com/pyca/cryptography/pull/10759
- [ ] https://github.com/pyca/cryptography/pull/10761
- [ ] https://github.com/pyca/cryptography/pull/10758
- [ ] https://github.com/pyca/cryptography/pull/10760
- [x] `src/x509/common.rs`
- [ ] https://github.com/pyca/cryptography/pull/10756
- [x] `src/x509/extensions.rs`
- [x] `src/x509/sign.rs`
- [ ] https://github.com/pyca/cryptography/pull/10804
```

```[tasklist]
### Cleanup
- [ ] https://github.com/pyca/cryptography/pull/10801
- [x] Remove all calls to `into_gil_ref()`
- [ ] https://github.com/pyca/cryptography/pull/10803
```

**Comment by alex** [comment]
We're done here!

**Comment by davidhewitt** [comment]
Great! Seems like I can release PyO3 0.21.2 without needing further changes!
