### ISSUE TITLE
Change key loading APIs to not require knowing so much stuff

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#1269]
Specifically it seems like there's consensus on just moving to `load_pem_private_key` and `load_pem_public_key`.
## Tasks
- [x] Introduce new interface `PEMLoadingBackend` or something.
- [x] Expose public API for it.
- [x] Implement interface on OpenSSL backend.
- [x] Deprecate old interface, and implementation
- [x] Add new `load_pem_public_key` API.
