### ISSUE TITLE
Support loading of DER private/public keys

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1573]
We've implemented PEM loading, now it's time for DER.

refs #614

- [x] Add DER encoded keys (#1607)
- [x] Add backend interface (#1608)
- [x] Add multibackend support (#1609)
- [ ] Add OpenSSL support + tests

**Comment by alex** [comment]
This is done.
