### ISSUE TITLE
Final 1.0 Checklist

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2249]
The final blockers before we can release 1.0:

- [x] Split extensions out of the x509 base module
- [x] update x509 docs for oid namespaces
- [x] Update the code/doctest examples to use the new namespaces
