### ISSUE TITLE
Add tests for new wycheproof vectors since c313761979d74b0417230eddd0f87d0cfab2b46b

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#5075]
Wycheproof just landed a bunch of new vectors! We need to add tests for them.

- [ ] ~~`testvectors/aead_aes_siv_cmac_test.json`~~
- [ ] ~~`testvectors/aegis128L_test.json`~~
- [ ] ~~`testvectors/aegis128_test.json`~~
- [ ] ~~`testvectors/aegis256_test.json`~~
- [ ] ~~`testvectors/dsa_2048_224_sha224_p1363_test.json`~~
- [x] `testvectors/dsa_2048_224_sha224_test.json` (#5098)
- [ ] ~~`testvectors/dsa_2048_224_sha256_p1363_test.json`~~
- [x] `testvectors/dsa_2048_224_sha256_test.json` (#5098)
- [ ] ~~`testvectors/dsa_2048_256_sha256_p1363_test.json`~~
- [x] `testvectors/dsa_2048_256_sha256_test.json` (#5098)
- [ ] ~~`testvectors/dsa_3072_256_sha256_p1363_test.json`~~
- [x] `testvectors/dsa_3072_256_sha256_test.json` (#5098)
- [ ] ~~`testvectors/ecdsa_brainpoolP224r1_sha224_p1363_test.json`~~
- [ ] ~~`testvectors/ecdsa_brainpoolP256r1_sha256_p1363_test.json`~~
- [ ] ~~`testvectors/ecdsa_brainpoolP320r1_sha384_p1363_test.json`~~
- [ ] ~~`testvectors/ecdsa_brainpoolP384r1_sha384_p1363_test.json`~~
- [ ] ~~`testvectors/ecdsa_brainpoolP512r1_sha512_p1363_test.json`~~
- [ ] ~~`testvectors/ecdsa_secp224r1_sha224_p1363_test.json`~~
- [ ] ~~`testvectors/ecdsa_secp224r1_sha256_p1363_test.json`~~
- [x] `testvectors/ecdsa_secp224r1_sha3_224_test.json` (#5099)
- [x] `testvectors/ecdsa_secp224r1_sha3_256_test.json` (#5099)
- [x] `testvectors/ecdsa_secp224r1_sha3_512_test.json` (#5099)
- [ ] ~~`testvectors/ecdsa_secp224r1_sha512_p1363_test.json`~~
- [ ] ~~`testvectors/ecdsa_secp256k1_sha256_p1363_test.json`~~
- [x] `testvectors/ecdsa_secp256k1_sha3_256_test.json` (#5099)
- [x] `testvectors/ecdsa_secp256k1_sha3_512_test.json` (#5099)
- [ ] ~~`testvectors/ecdsa_secp256k1_sha512_p1363_test.json`~~
- [ ] ~~`testvectors/ecdsa_secp256r1_sha256_p1363_test.json`~~
- [x] `testvectors/ecdsa_secp256r1_sha3_256_test.json` (#5099)
- [x] `testvectors/ecdsa_secp256r1_sha3_512_test.json` (#5099)
- [ ] ~~`testvectors/ecdsa_secp256r1_sha512_p1363_test.json`~~
- [ ] ~~`testvectors/ecdsa_secp384r1_sha384_p1363_test.json`~~
- [x] `testvectors/ecdsa_secp384r1_sha3_384_test.json` (#5099)
- [x] `testvectors/ecdsa_secp384r1_sha3_512_test.json` (#5099)
- [ ] ~~`testvectors/ecdsa_secp384r1_sha512_p1363_test.json`~~
- [x] `testvectors/ecdsa_secp521r1_sha3_512_test.json` (#5099)
- [ ] ~~`testvectors/ecdsa_secp521r1_sha512_p1363_test.json`~~
- [x] `testvectors/ed448_test.json`
- [ ] ~~`testvectors/gmac_test.json`~~
- [x] `testvectors/hkdf_sha1_test.json`
- [x] `testvectors/hkdf_sha256_test.json`
- [x] `testvectors/hkdf_sha384_test.json`
- [x] `testvectors/hkdf_sha512_test.json`
- [ ] ~~`testvectors/primality_test.json`~~
- [x] `testvectors/rsa_oaep_2048_sha1_mgf1sha1_test.json` (#5100)
- [x] `testvectors/rsa_oaep_2048_sha224_mgf1sha1_test.json` (#5100)
- [x] `testvectors/rsa_oaep_2048_sha224_mgf1sha224_test.json` (#5100)
- [x] `testvectors/rsa_oaep_2048_sha256_mgf1sha1_test.json` (#5100)
- [x] `testvectors/rsa_oaep_2048_sha256_mgf1sha256_test.json` (#5100)
- [x] `testvectors/rsa_oaep_2048_sha384_mgf1sha1_test.json` (#5100)
- [x] `testvectors/rsa_oaep_2048_sha384_mgf1sha384_test.json` (#5100)
- [x] `testvectors/rsa_oaep_2048_sha512_mgf1sha1_test.json` (#5100)
- [x] `testvectors/rsa_oaep_2048_sha512_mgf1sha512_test.json` (#5100)
- [x] `testvectors/rsa_oaep_3072_sha256_mgf1sha1_test.json` (#5100)
- [x] `testvectors/rsa_oaep_3072_sha256_mgf1sha256_test.json` (#5100)
- [x] `testvectors/rsa_oaep_3072_sha512_mgf1sha1_test.json` (#5100)
- [x] `testvectors/rsa_oaep_3072_sha512_mgf1sha512_test.json` (#5100)
- [x] `testvectors/rsa_oaep_4096_sha256_mgf1sha1_test.json` (#5100)
- [x] `testvectors/rsa_oaep_4096_sha256_mgf1sha256_test.json` (#5100)
- [x] `testvectors/rsa_oaep_4096_sha512_mgf1sha1_test.json` (#5100)
- [x] `testvectors/rsa_oaep_4096_sha512_mgf1sha512_test.json` (#5100)
- [x] `testvectors/rsa_oaep_misc_test.json` (#5100)
- [x] `testvectors/rsa_pkcs1_2048_test.json` (#5234)
- [x] `testvectors/rsa_pkcs1_3072_test.json` (#5234)
- [x] `testvectors/rsa_pkcs1_4096_test.json` (#5234)
- [x] `testvectors/rsa_pss_2048_sha512_256_mgf1_28_test.json` (#5237)
- [x] `testvectors/rsa_pss_2048_sha512_256_mgf1_32_test.json` (#5237)
- [x] `testvectors/rsa_sig_gen_misc_test.json` (#5237)
- [x] `testvectors/rsa_signature_2048_sha384_test.json` (#5078)
- [x] `testvectors/rsa_signature_2048_sha3_224_test.json` (#5078)
- [x] `testvectors/rsa_signature_2048_sha3_256_test.json` (#5078)
- [x] `testvectors/rsa_signature_2048_sha3_384_test.json` (#5078)
- [x] `testvectors/rsa_signature_2048_sha3_512_test.json` (#5078)
- [x] `testvectors/rsa_signature_2048_sha512_224_test.json` (#5078)
- [x] `testvectors/rsa_signature_2048_sha512_256_test.json` (#5078)
- [x] `testvectors/rsa_signature_3072_sha3_256_test.json` (#5078)
- [x] `testvectors/rsa_signature_3072_sha3_384_test.json` (#5078)
- [x] `testvectors/rsa_signature_3072_sha3_512_test.json` (#5078)
- [x] `testvectors/rsa_signature_3072_sha512_256_test.json` (#5078)
- [x] `testvectors/rsa_signature_4096_sha512_256_test.json` (#5078)
- [ ] ~~`testvectors/vmac_128_test.json`~~
- [ ] ~~`testvectors/vmac_64_test.json`~~
- [ ] `testvectors/x25519_asn_test.json`
- [ ] `testvectors/x25519_jwk_test.json`
- [ ] `testvectors/x25519_pem_test.json`
- [ ] `testvectors/x448_asn_test.json`
- [ ] `testvectors/x448_jwk_test.json`
- [ ] `testvectors/x448_pem_test.json`
- [x] `testvectors/x448_test.json` (#5077)
- [ ] ~~`testvectors/xchacha20_poly1305_test.json`~~

**Comment by alex** [comment]
Ok, I think we're good here.
